### ISSUE TITLE
Создать статические части главной страницы

### ISSUE THREAD

**Issue by Gyxer513** [LiteraExcurs/frontend#2]
Необходимо сверстать Header, About, Guids и Footer. Начинаем с версии для десктопа.

**Comment by anastasia-bazaeva** [comment]
@Gyxer513 если можно, давай попросим заказчика найти иконки из единого набора, потому что сейчас у нас в макете целый зоопарк разных иконок, и ни один стиль иконок не повторяется ни в цвете, ни в чб, все иконки разные из разных наборов.

![Image](https://github.com/LiteraExcurs/frontend/assets/102751317/bf48d767-6ff0-4e0c-9d7b-ba07dde18acf)
![Image](https://github.com/LiteraExcurs/frontend/assets/102751317/2156e3b3-fbe6-42fb-b2a1-d099cb2ecf5a)

**Comment by Gyxer513** [comment]
@anastasia-bazaeva Привет! В макет внесены правки. Теперь иконки везде одинаковые. 



![Image](https://github.com/LiteraExcurs/frontend/assets/102280477/1c749bb4-d46b-4571-9f97-a5015cbb2126)
