### ISSUE TITLE
Сделать компонент кнопки

### ISSUE THREAD

**Issue by Gyxer513** [LiteraExcurs/frontend#4]
Объединил две задачи в одну. 

В проекте используются кнопки разных цветов, необходимо сделать их одним компонентом. 

![Image](https://github.com/LiteraExcurs/frontend/assets/102280477/859d40a9-1fcf-4d4f-8385-3924fdbe6590)

![Image](https://github.com/LiteraExcurs/frontend/assets/102280477/ee3309cb-8287-45a8-8755-b086997232f2)

**Comment by vierim** [comment]
@Gyxer513 Подскажи, правильно я понимаю, что вот эти элементы тоже входят в данную задачу:
- кнопка в футере - [https://disk.yandex.ru/i/0RrfaNAu4bruxA](https://disk.yandex.ru/i/0RrfaNAu4bruxA)
- кнопки на страницах экскурсий - [https://disk.yandex.ru/i/GdEtHp-5tgXuUQ](https://disk.yandex.ru/i/GdEtHp-5tgXuUQ)

**Comment by Gyxer513** [comment]
@vierim Привет, да это один компонент. Если есть различия в макете, можно подогнать под один.
