### ISSUE TITLE
Сделать авторизацию на фронте

### ISSUE THREAD

**Issue by Gyxer513** [LiteraExcurs/frontend#6]
Нужно сверстать поле для ввода логина/пароля. Сделать защищенный роут.

**Comment by anastasia-bazaeva** [comment]
В react-admin оказался свой инструмент для подключения авторизации, в котором есть поля для ввода. Нам подойдет или мы хотим свой вид?

![Image](https://github.com/LiteraExcurs/frontend/assets/102751317/c1a5af4c-f125-4fb7-aca7-030ef235675c)

**Comment by Gyxer513** [comment]
Используем готовое решение, в этом то его смысл, проблему с языком решим либо позже, либо оставим так.
